[package]
name = "jindex"
version = "0.1.0"
authors = ["Clark Kampfe <clark.kampfe@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
structopt = "0.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
