[package]
name = "jindex"
version = "0.1.0"
authors = ["Clark Kampfe <clark.kampfe@gmail.com>"]
edition = "2018"

[dependencies]
jemalloc = { package = "jemallocator", version = "0.3", optional = true }
serde_json = "1.0"
structopt = "0.3"

[target.'cfg(target_family = "unix")'.dependencies]
nix = "0.18"

[features]
default = ["jemalloc"]

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
